name: oss-compliance-universal

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  compliance:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # ---------- Setup ----------
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up GitHub CLI
        uses: cli/cli-action@v2

      # ---------- SCANOSS ----------
      - name: Install SCANOSS CLI
        run: pip install scanoss

      - name: Run SCANOSS Scan
        run: scanoss scan -o scanoss-results.json .

      # ---------- Syft ----------
      - name: Install Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Run Syft SBOM
        run: syft dir:. -o spdx-json > $GITHUB_WORKSPACE/syft-sbom.spdx.json

      # ---------- ORT ----------
      - name: Download ORT CLI using GitHub CLI
        run: |
          gh release download v2024.03.11 \
            --repo oss-review-toolkit/ort \
            --pattern "ort-2024.03.11.jar"

      - name: Verify ORT JAR
        run: file ort-2024.03.11.jar

      - name: Run ORT Scan
        run: java -jar ort-2024.03.11.jar analyze -i . -o ort-results

      # ---------- Report Generation ----------
      - name: Install Python Dependencies for Report Generation
        run: pip install -r requirements.txt

      - name: Generate Compliance Excel Reports
        run: |
          python3 generate_excel_merge_syft_scanoss.py $GITHUB_WORKSPACE/syft-sbom.spdx.json $GITHUB_WORKSPACE/scanoss-results.json

      # ---------- Upload Excel Reports ----------
      - name: Upload Compliance Excel Reports
        uses: actions/upload-artifact@v3
        with:
          name: compliance-reports
          path: |
            compliance_merged_report.xlsx
            syft_components_report.xlsx
            scanoss_components_report.xlsx

      # ---------- Upload JSON Outputs ----------
      - name: Upload Syft SBOM JSON
        uses: actions/upload-artifact@v3
        with:
          name: syft-sbom-json
          path: syft-sbom.spdx.json

      - name: Upload SCANOSS Results JSON
        uses: actions/upload-artifact@v3
        with:
          name: scanoss-results-json
          path: scanoss-results.json

      - name: Upload ORT Analyzer JSON
        uses: actions/upload-artifact@v3
        with:
          name: ort-analyzer-json
          path: ort-results/analyzer-result.json

      - name: Upload ORT Analyzer YAML
        uses: actions/upload-artifact@v3
        with:
          name: ort-analyzer-yaml
          path: ort-results/analyzer-result.yml
